import { DisposableResult } from "../types";

const DISPOSABLE_DOMAINS = new Set([
  "mailinator.com",
  "guerrillamail.com",
  "guerrillamail.net",
  "guerrillamail.biz",
  "guerrillamail.org",
  "sharklasers.com",
  "grr.la",
  "tempmail.com",
  "tempmail.net",
  "10minutemail.com",
  "10minutemail.net",
  "yopmail.com",
  "yopmail.fr",
  "yopmail.net",
  "cool.fr.nf",
  "courriel.fr.nf",
  "mega.zippyimage.com",
  "trashmail.com",
  "trashmail.net",
  "trashmail.org",
  "dispostable.com",
  "getairmail.com",
  "burnermail.io",
  "throwawaymail.com",
  "fakemailgenerator.com",
  "emailondeck.com",
  "crazymailing.com",
  "maildrop.cc",
  "inboxkitten.com",
  "temp-mail.org",
  "mytemp.email",
  "nada.ltd",
  "getnada.com",
  "mohmal.com",
  "generator.email",
  "zillamail.com",
  "burnermail.org",
  "dropmail.me",
  "minuteinbox.com",
  "harakirimail.com",
  "sharklasers.com",
  "spam4.me",
  "binkmail.com",
  "safetymail.info",
  "trashymail.com",
  "mailcatch.com",
  "disposablemail.com",
  "fakeinbox.com",
]);

const FREE_PROVIDERS = new Set([
  "gmail.com",
  "googlemail.com",
  "yahoo.com",
  "yahoo.co.uk",
  "yahoo.fr",
  "yahoo.de",
  "yahoo.es",
  "yahoo.it",
  "yahoo.co.jp",
  "ymail.com",
  "rocketmail.com",
  "hotmail.com",
  "hotmail.co.uk",
  "hotmail.fr",
  "hotmail.de",
  "hotmail.es",
  "hotmail.it",
  "outlook.com",
  "outlook.fr",
  "outlook.de",
  "outlook.es",
  "live.com",
  "live.co.uk",
  "live.fr",
  "msn.com",
  "icloud.com",
  "me.com",
  "mac.com",
  "aol.com",
  "aim.com",
  "protonmail.com",
  "proton.me",
  "zoho.com",
  "mail.com",
  "email.com",
  "gmx.com",
  "gmx.net",
  "gmx.de",
  "web.de",
  "yandex.com",
  "yandex.ru",
  "mail.ru",
  "inbox.ru",
  "bk.ru",
  "list.ru",
  "tutanota.com",
  "tuta.io",
  "fastmail.com",
]);

const ROLE_BASED_PREFIXES = new Set([
  "admin",
  "administrator",
  "info",
  "support",
  "help",
  "sales",
  "contact",
  "contactus",
  "hello",
  "hi",
  "team",
  "staff",
  "office",
  "desk",
  "billing",
  "accounts",
  "finance",
  "invoices",
  "payment",
  "payments",
  "hr",
  "humanresources",
  "jobs",
  "careers",
  "recruiting",
  "recruitment",
  "marketing",
  "press",
  "media",
  "pr",
  "news",
  "newsletter",
  "legal",
  "compliance",
  "privacy",
  "security",
  "abuse",
  "postmaster",
  "hostmaster",
  "webmaster",
  "root",
  "sysadmin",
  "system",
  "operations",
  "ops",
  "devops",
  "dev",
  "developer",
  "engineering",
  "it",
  "tech",
  "support-team",
  "noreply",
  "no-reply",
  "donotreply",
  "do-not-reply",
  "notification",
  "notifications",
  "alerts",
  "alert",
  "updates",
  "update",
  "mail",
  "mailer",
  "bounce",
  "feedback",
  "enquiries",
  "enquiry",
  "inquiry",
  "inquiries",
]);

export function checkDisposableAndRole(localPart: string, domain: string): DisposableResult {
  const normDomain = domain.toLowerCase().trim();
  const normLocal = localPart.toLowerCase().trim().replace(/[._-]/g, "");

  const isDisposable = DISPOSABLE_DOMAINS.has(normDomain);
  const isFreeProvider = FREE_PROVIDERS.has(normDomain);

  let isRole = false;
  for (const role of ROLE_BASED_PREFIXES) {
    const cleanRole = role.replace(/[._-]/g, "");
    if (normLocal === cleanRole || normLocal.startsWith(cleanRole)) {
      isRole = true;
      break;
    }
  }

  let providerName: string | null = null;
  if (isDisposable) {
    providerName = normDomain.split(".")[0];
    providerName = providerName.charAt(0).toUpperCase() + providerName.slice(1);
  } else if (isFreeProvider) {
    providerName = normDomain.split(".")[0];
    providerName = providerName.charAt(0).toUpperCase() + providerName.slice(1);
  }

  return {
    is_disposable: isDisposable,
    is_free_provider: isFreeProvider,
    is_role_based: isRole,
    provider_name: providerName,
  };
}
